### ISSUE TITLE
test with a given video file

### ISSUE THREAD

**Issue by sasin07** [PJunhyuk/read-daly#1]
I want to demonstrate how to input a single video and get the result corresponding to that video. can i do that?

**Comment by PJunhyuk** [comment]
Hi. Thanks for your interest!  

This repo just read and show videos in [DALY dataset](http://thoth.inrialpes.fr/daly/), so you can't use it for your OWN video.  

If you mean how to get result of exact video in DALY dataset, you can check Usage in [README.md](https://github.com/PJunhyuk/read-daly/blob/master/README.md).

**Comment by sasin07** [comment]
I want to evaluate actions with my input video.  Is it possible

**Comment by PJunhyuk** [comment]
No. You can't do that by using this repo.

You have to implement codes additionally which recognizing actions on video, using this repo.

Maybe you can check [charades-algorithms](https://github.com/PJunhyuk/charades-algorithms) repo.

**Comment by sasin07** [comment]
thank you for help.. I will try that project.
